#!/usr/bin/expect -f
#
#                      Leader
#                      /    \
#                   SSED1  SSED2
#                     \     / \
#                      \   /   \
#                       WED1  WED2
source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

set LEADER 1
set SSED1 2
set SSED2 3
set WED1 4
set WED2 5

send_user ">>> setup leader\n"
spawn_node $LEADER
setup_default_network
attach "leader"


send_user ">>> setup SSED1\n"
spawn_node $SSED1
setup_default_network
run_command "mode -"
attach "child"
set ssed1_extaddr [get_extaddr]


send_user ">>> setup SSED2\n"
spawn_node $SSED2
setup_default_network
run_command "mode -"
attach "child"
set ssed2_extaddr [get_extaddr]


send_user ">>> setup leader topology\n"
switch_node $LEADER
run_command "macfilter addr add $ssed1_extaddr"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"


send_user ">>> setup WED1\n"
spawn_node $WED1
setup_default_network
run_command "mode -"
run_command "wakeup channel 25"
run_command "wakeup parameters 1000000 8000"
run_command "wakeup listen enable"
run_command "macfilter addr add $ssed1_extaddr"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"
set wed1_lladdr [get_ipaddr linklocal]
set wed1_extaddr [get_extaddr]


send_user ">>> setup WED2\n"
spawn_node $WED2
setup_default_network
run_command "mode -"
run_command "wakeup channel 25"
run_command "wakeup parameters 1000000 8000"
run_command "wakeup listen enable"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"
set wed2_lladdr [get_ipaddr linklocal]
set wed2_extaddr [get_extaddr]


send_user ">>> SSED1 wake up WED1\n"
switch_node $SSED1
run_command "srp server enable"
run_command "wakeup wake $wed1_extaddr 7500 1090"
sleep 5
run_command "srp server host" "$wed1_lladdr"
send "ping $wed1_lladdr\n"
expect_line "Done"

send_user ">>> SSED1 wake up WED2\n"
run_command "wakeup wake $wed2_extaddr 7500 1090"
sleep 5
run_command "srp server host" "$wed2_lladdr"
send "ping $wed2_lladdr\n"
expect_line "Done"


send_user ">>> SSED2 wake up WED1\n"
swich_node $SSED2
run_command "srp server enable"
run_command "wakeup wake $wed1_extaddr 7500 1090"
sleep 5
run_command "srp server host" "$wed1_lladdr"
send "ping $wed1_lladdr\n"
expect_line "Done"
