#!/usr/bin/expect -f
#
#  Copyright (c) 2021, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

# This script verifies a SED act as a border router.

#
#
# SED(POSIX) -- Leader -- R
#

source "tests/scripts/expect/_common.exp"

spawn_node 2 cli
setup_default_network

send "ifconfig up\n"
expect "Done"
send "thread start\n"
expect "Done"

set extaddr2 [get_extaddr]

wait_for "state" "leader"
sleep 3

spawn_node 3 cli
setup_default_network

send "macfilter addr add ${extaddr2}\n"
expect_line "Done"

send "macfilter addr allowlist\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "router"
sleep 4

spawn_node 1
send "mode -\n"
expect "Done"
setup_default_network

send "ifconfig up\n"
expect "Done"
send "thread start\n"
expect "Done"
wait_for "state" "child"
sleep 4

send "prefix add fd22:33::/64 paros\n"
expect "Done"
send "netdata register\n"
expect "Done"
send "pollperiod 500\n"
expect "Done"

sleep 2

set hostip "fd77:88:0:0:0:0:0:1"
set hostif "eno1"
try {
    send_user "ip addr add $hostip/64 dev $hostif"
    exec ip addr add $hostip/64 dev $hostif

    sleep 3

    switch_node 3
    send "ping ${hostip}\n"
    expect_line "Done"
    expect "16 bytes from $hostip: icmp_seq=1"
} finally {
    catch {exec ip addr del $hostip/64 dev $hostif}
}
